"""
Verify the 4class labels generated by split_multirm.py
"""
import numpy as np
import os

# Check the generated 4class files
base_dir = "npy/multirm/51split"
mods = ['Am','Cm','Gm','Um','m1A','m5C','m5U','m6A','m6Am','m7G','Psi','AtoI']

# Expected mapping
expected_mapping = {
    'Am': 0,   # A
    'Cm': 1,   # C
    'Gm': 2,   # G
    'Um': 3,   # U
    'm1A': 0,  # A
    'm5C': 1,  # C
    'm5U': 3,  # U
    'm6A': 0,  # A
    'm6Am': 0, # A
    'm7G': 2,  # G
    'Psi': 3,  # U
    'AtoI': 0  # A
}

print("=" * 60)
print("验证生成的4类标签文件")
print("=" * 60)

# Check train data for a few classes
test_mods = ['Am', 'Cm', 'm6A', 'Psi']

for mod in test_mods:
    print(f"\n检查 {mod}:")
    
    # Check positive samples
    pos_out_4class = np.load(os.path.join(base_dir, mod, "pos", "train_out_4class.npy"))
    pos_out = np.load(os.path.join(base_dir, mod, "pos", "train_out.npy"))
    
    print(f"  正样本数: {len(pos_out_4class)}")
    print(f"  12类标签示例: {pos_out[0]}")
    print(f"  4类标签示例: {pos_out_4class[0]}")
    
    # Find the expected group index
    expected_group = expected_mapping[mod]
    print(f"  预期组索引: {expected_group}")
    
    # Verify all positive samples have correct 4class label
    all_correct = all(np.argmax(pos_out_4class, axis=1) == expected_group)
    print(f"  所有正样本4类标签正确: {all_correct}")
    
    # Check negative samples
    neg_out_4class = np.load(os.path.join(base_dir, mod, "neg", "train_out_4class.npy"))
    all_zeros = np.all(neg_out_4class == 0)
    print(f"  负样本数: {len(neg_out_4class)}")
    print(f"  所有负样本4类标签为0: {all_zeros}")

print("\n" + "=" * 60)
print("验证完成！")
print("=" * 60)